import "../styles/about-style.css"

export const aboutPage = ()=>{
    const content = document.createElement('div');
    content.setAttribute('class', 'content');
    content.innerHTML = `<div class='block'><p class='heading'>OUR DNA</p><p class='para'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec aliquet risus, vel facilisis sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer quis neque convallis, convallis enim quis, imperdiet magna. Curabitur volutpat odio eu suscipit porta. Aliquam accumsan, ex eget congue vestibulum, elit neque efficitur tortor, at lacinia augue erat nec nisl. Ut arcu tortor, tempor vitae rhoncus id, consequat id enim. Aliquam eget diam lorem. Ut sem elit, eleifend sed lorem non, finibus feugiat erat. Morbi semper ante velit. Vivamus ultrices leo mi, eu tristique sapien venenatis eget. Nam in ultrices erat. Cras venenatis ipsum sed sagittis euismod. Sed mattis neque non neque venenatis cursus. Duis tincidunt a risus sit amet placerat. In luctus neque in libero varius auctor.</p></div>

<div class='block'><p class='heading'>THE JOURNEY</p><p class='para'>Phasellus sodales ligula ac nulla consectetur, sed rutrum magna posuere. Etiam auctor quam risus, sit amet tristique est molestie quis. Fusce ullamcorper feugiat lectus nec ultricies. Vestibulum interdum tempus urna, in vestibulum arcu tristique at. Morbi magna sem, ultricies ac tristique vel, congue vel velit. Donec eu placerat ex. Nunc porta urna molestie diam finibus, sed suscipit eros varius. Vestibulum interdum eget massa vitae varius. Suspendisse blandit dictum lacus, in ultrices est euismod eu. Nam bibendum ipsum diam, sit amet sollicitudin lorem varius nec. Donec in ligula at risus suscipit convallis vitae eu turpis. Ut sit amet suscipit risus, at commodo erat. Proin nunc purus, sodales mattis libero eu, convallis efficitur est. Donec sit amet sem a ex congue dignissim. 
Mauris venenatis purus a tristique efficitur. Morbi vitae neque ac ex laoreet aliquet a ut velit. Donec maximus nibh sit amet ligula viverra aliquet. Nulla eu ligula mauris. Aliquam vitae enim sem. Donec porttitor, orci eu fringilla lacinia, sapien lacus luctus leo, eu cursus tellus lorem ut mauris. Maecenas magna odio, vehicula vel dolor at, tempus fringilla diam. Aliquam porta tristique massa nec viverra. In malesuada ipsum eget arcu pretium porta.Vivamus pulvinar dapibus tortor, sit amet consequat nibh eleifend at. Praesent auctor convallis diam at vehicula. Integer porttitor erat nec ex consectetur, eu scelerisque nulla consequat. Suspendisse fermentum lectus eleifend, sollicitudin massa rutrum, cursus libero. Sed quis libero pretium, malesuada dolor non, sagittis sapien. Etiam ac facilisis felis. Nunc ultricies, elit efficitur hendrerit 
elementum, odio metus ullamcorper nibh, a congue nisi purus eget ex. Cras in congue magna, et porta velit. Praesent sed libero id nisl consequat pellentesque sed ut ligula. Quisque ullamcorper dolor enim, ut lacinia lectus aliquet posuere. Vestibulum interdum consequat neque ut egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p></div>

<div class='block'><p class='heading'>THE FURTHER</p><p class='para'>Cras feugiat ultrices commodo. Proin in magna rhoncus, venenatis ipsum euismod, mattis turpis. Cras fringilla quam et placerat ornare. Mauris commodo neque non risus faucibus, nec cursus orci commodo. Vivamus luctus mauris in ipsum facilisis, vitae rhoncus turpis aliquet. Ut egestas fermentum massa vitae interdum. Quisque rhoncus lacinia cursus. Pellentesque sollicitudin pretium lacus, in tristique risus vehicula sit amet. Curabitur porta elit eget mattis tincidunt. Suspendisse ac malesuada purus. Nullam laoreet blandit porttitor. Cras convallis arcu nec tellus tempor rutrum. Sed accumsan eros id tincidunt pellentesque.</p></div>`

return content;
}